/**
 * Image registry — shared types + non-portfolio assets.
 *
 * Portfolio photography is sourced from `./portfolio.ts`, which is
 * auto-generated by `scripts/import-portfolio.mjs` from the per-project
 * folders under `/Users/vortex/Downloads/Mobiliere`. Each project keeps
 * its own folder under `public/images/portfolio/<cat>/<projectSlug>/`
 * with screen-size thumbs (`NN.jpeg`) and originals (`full/NN.jpeg`).
 */

import type { Locale, PortfolioCategorySlug } from '../i18n/config'
import { portfolioProjects } from './portfolio'

export interface ImageRef {
  src: string
  alt: Record<'ro' | 'en', string>
  width?: number
  height?: number
  /** Path to the original-resolution image; opened in a new tab on click. */
  full?: string
}

export function pickAlt(img: ImageRef, locale: string): string {
  if (locale === 'ro' || locale === 'en') return img.alt[locale]
  return img.alt.ro
}

export const heroImages: ImageRef[] = [
  { src: '/images/hero/hero-bucatarie-landscape-1.jpeg', alt: { ro: 'Bucătărie pe comandă realizată de Arti Studio în Oradea', en: 'Custom kitchen built by Arti Studio in Oradea' } },
]

export const homeHero: ImageRef = heroImages[0]

/**
 * Home-page portfolio picks — first project's cover per category.
 * Consumed by `<PortfolioGrid>` on the landing page.
 */
export const homePortfolioPicks: Array<{ category: PortfolioCategorySlug; image: ImageRef }> = (
  ['bucatarie', 'living', 'dormitor', 'dressing'] as const
).map((category) => {
  const project = portfolioProjects.find((p) => p.category === category)
  if (!project) throw new Error(`homePortfolioPicks: no project for ${category}`)
  return { category, image: project.cover }
})

/**
 * Locale-aware narrow alt-picker used inside route components.
 * Falls back to Romanian for the 13 stubbed locales.
 */
export function localeAlt(img: ImageRef, locale: Locale): string {
  return locale === 'en' ? img.alt.en : img.alt.ro
}

/**
 * Service offerings — bilingual alt text per slot. `src` stays undefined
 * until real photography is supplied; the `<ServiceCard>` falls back to
 * `<ServicePlaceholder>` while empty. Order matches the `servicii.items`
 * array in every locale (01..06).
 */
export interface ServiceImageRef {
  src?: string
  alt: Record<'ro' | 'en', string>
}

export const serviceImages: ServiceImageRef[] = [
  { alt: { ro: 'Atelier de design și proiectare 3D — Arti Studio Oradea', en: '3D design and drafting studio — Arti Studio Oradea' } },
  { alt: { ro: 'Măsurători la fața locului — Arti Studio Oradea', en: 'On-site measurements — Arti Studio Oradea' } },
  { alt: { ro: 'Producție de mobilier la comandă în atelier — Arti Studio Oradea', en: 'Custom furniture production in the workshop — Arti Studio Oradea' } },
  { alt: { ro: 'Montaj și finisaje la cheie — Arti Studio Oradea', en: 'Turnkey installation and finishing — Arti Studio Oradea' } },
  { alt: { ro: 'Feronerie și materiale premium — Arti Studio Oradea', en: 'Premium hardware and materials — Arti Studio Oradea' } },
  { alt: { ro: 'Suport post-instalare și garanție — Arti Studio Oradea', en: 'Post-install support and warranty — Arti Studio Oradea' } },
]
