// Auto-generated by scripts/import-portfolio.mjs
import type { PortfolioCategorySlug } from '../i18n/config'
import type { ImageRef } from './images'

export interface PortfolioProject {
  id: string
  category: PortfolioCategorySlug
  slug: string
  /** Display title; defaults to a generic '<Category> · Proiect N' label. */
  title: { ro: string; en: string }
  cover: ImageRef
  images: ImageRef[]
}

export const portfolioProjects: PortfolioProject[] = [
  {
    id: 'baie-baie-1',
    category: 'baie',
    slug: 'baie-1',
    title: { ro: "Baie · Proiect 01", en: "Bathroom · Project 01" },
    cover: { src: '/images/portfolio/baie/baie-1/01.jpeg', full: '/images/portfolio/baie/baie-1/full/01.jpeg', width: 533, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom bathroom — Arti Studio Oradea (project 1)" } },
    images: [
      { src: '/images/portfolio/baie/baie-1/01.jpeg', full: '/images/portfolio/baie/baie-1/full/01.jpeg', width: 533, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom bathroom — Arti Studio Oradea (project 1)" } },
    ],
  },
  {
    id: 'baie-baie-2',
    category: 'baie',
    slug: 'baie-2',
    title: { ro: "Baie · Proiect 02", en: "Bathroom · Project 02" },
    cover: { src: '/images/portfolio/baie/baie-2/01.jpeg', full: '/images/portfolio/baie/baie-2/full/01.jpeg', width: 600, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bathroom — Arti Studio Oradea (project 2)" } },
    images: [
      { src: '/images/portfolio/baie/baie-2/01.jpeg', full: '/images/portfolio/baie/baie-2/full/01.jpeg', width: 600, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bathroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/baie/baie-2/02.jpeg', full: '/images/portfolio/baie/baie-2/full/02.jpeg', width: 600, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bathroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/baie/baie-2/03.jpeg', full: '/images/portfolio/baie/baie-2/full/03.jpeg', width: 600, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bathroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/baie/baie-2/04.jpeg', full: '/images/portfolio/baie/baie-2/full/04.jpeg', width: 600, height: 800, alt: { ro: "Baie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bathroom — Arti Studio Oradea (project 2)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-1',
    category: 'bucatarie',
    slug: 'bucatarie-1',
    title: { ro: "Bucătărie · Proiect 01", en: "Kitchen · Project 01" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-1/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-1/full/01.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom kitchen — Arti Studio Oradea (project 1)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-1/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-1/full/01.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom kitchen — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-1/02.jpeg', full: '/images/portfolio/bucatarie/bucatarie-1/full/02.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom kitchen — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-1/03.jpeg', full: '/images/portfolio/bucatarie/bucatarie-1/full/03.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom kitchen — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-1/04.jpeg', full: '/images/portfolio/bucatarie/bucatarie-1/full/04.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom kitchen — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-1/05.jpeg', full: '/images/portfolio/bucatarie/bucatarie-1/full/05.jpeg', width: 504, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom kitchen — Arti Studio Oradea (project 1)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-2',
    category: 'bucatarie',
    slug: 'bucatarie-2',
    title: { ro: "Bucătărie · Proiect 02", en: "Kitchen · Project 02" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-2/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-2/full/01.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom kitchen — Arti Studio Oradea (project 2)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-2/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-2/full/01.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom kitchen — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-2/02.jpeg', full: '/images/portfolio/bucatarie/bucatarie-2/full/02.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom kitchen — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-2/03.jpeg', full: '/images/portfolio/bucatarie/bucatarie-2/full/03.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom kitchen — Arti Studio Oradea (project 2)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-3',
    category: 'bucatarie',
    slug: 'bucatarie-3',
    title: { ro: "Bucătărie · Proiect 03", en: "Kitchen · Project 03" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-3/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/01.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-3/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/01.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-3/02.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/02.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-3/03.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/03.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-3/04.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/04.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-3/05.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/05.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-3/06.jpeg', full: '/images/portfolio/bucatarie/bucatarie-3/full/06.jpeg', width: 800, height: 600, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom kitchen — Arti Studio Oradea (project 3)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-4',
    category: 'bucatarie',
    slug: 'bucatarie-4',
    title: { ro: "Bucătărie · Proiect 04", en: "Kitchen · Project 04" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-4/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-4/full/01.jpeg', width: 800, height: 533, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 4)", en: "Custom kitchen — Arti Studio Oradea (project 4)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-4/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-4/full/01.jpeg', width: 800, height: 533, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 4)", en: "Custom kitchen — Arti Studio Oradea (project 4)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-5',
    category: 'bucatarie',
    slug: 'bucatarie-5',
    title: { ro: "Bucătărie · Proiect 05", en: "Kitchen · Project 05" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-5/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-5/full/01.jpeg', width: 800, height: 533, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 5)", en: "Custom kitchen — Arti Studio Oradea (project 5)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-5/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-5/full/01.jpeg', width: 800, height: 533, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 5)", en: "Custom kitchen — Arti Studio Oradea (project 5)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-6',
    category: 'bucatarie',
    slug: 'bucatarie-6',
    title: { ro: "Bucătărie · Proiect 06", en: "Kitchen · Project 06" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-6/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-6/full/01.jpeg', width: 800, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 6)", en: "Custom kitchen — Arti Studio Oradea (project 6)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-6/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-6/full/01.jpeg', width: 800, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 6)", en: "Custom kitchen — Arti Studio Oradea (project 6)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-7',
    category: 'bucatarie',
    slug: 'bucatarie-7',
    title: { ro: "Bucătărie · Proiect 07", en: "Kitchen · Project 07" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-7/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-7/full/01.jpeg', width: 800, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 7)", en: "Custom kitchen — Arti Studio Oradea (project 7)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-7/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-7/full/01.jpeg', width: 800, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 7)", en: "Custom kitchen — Arti Studio Oradea (project 7)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-8',
    category: 'bucatarie',
    slug: 'bucatarie-8',
    title: { ro: "Bucătărie · Proiect 08", en: "Kitchen · Project 08" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-8/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-8/full/01.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 8)", en: "Custom kitchen — Arti Studio Oradea (project 8)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-8/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-8/full/01.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 8)", en: "Custom kitchen — Arti Studio Oradea (project 8)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-8/02.jpeg', full: '/images/portfolio/bucatarie/bucatarie-8/full/02.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 8)", en: "Custom kitchen — Arti Studio Oradea (project 8)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-8/03.jpeg', full: '/images/portfolio/bucatarie/bucatarie-8/full/03.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 8)", en: "Custom kitchen — Arti Studio Oradea (project 8)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-8/04.jpeg', full: '/images/portfolio/bucatarie/bucatarie-8/full/04.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 8)", en: "Custom kitchen — Arti Studio Oradea (project 8)" } },
    ],
  },
  {
    id: 'bucatarie-bucatarie-9',
    category: 'bucatarie',
    slug: 'bucatarie-9',
    title: { ro: "Bucătărie · Proiect 09", en: "Kitchen · Project 09" },
    cover: { src: '/images/portfolio/bucatarie/bucatarie-9/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-9/full/01.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 9)", en: "Custom kitchen — Arti Studio Oradea (project 9)" } },
    images: [
      { src: '/images/portfolio/bucatarie/bucatarie-9/01.jpeg', full: '/images/portfolio/bucatarie/bucatarie-9/full/01.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 9)", en: "Custom kitchen — Arti Studio Oradea (project 9)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-9/02.jpeg', full: '/images/portfolio/bucatarie/bucatarie-9/full/02.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 9)", en: "Custom kitchen — Arti Studio Oradea (project 9)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-9/03.jpeg', full: '/images/portfolio/bucatarie/bucatarie-9/full/03.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 9)", en: "Custom kitchen — Arti Studio Oradea (project 9)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-9/04.jpeg', full: '/images/portfolio/bucatarie/bucatarie-9/full/04.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 9)", en: "Custom kitchen — Arti Studio Oradea (project 9)" } },
      { src: '/images/portfolio/bucatarie/bucatarie-9/05.jpeg', full: '/images/portfolio/bucatarie/bucatarie-9/full/05.jpeg', width: 600, height: 800, alt: { ro: "Bucătărie pe comandă — Arti Studio Oradea (proiect 9)", en: "Custom kitchen — Arti Studio Oradea (project 9)" } },
    ],
  },
  {
    id: 'dormitor-dormitor-1',
    category: 'dormitor',
    slug: 'dormitor-1',
    title: { ro: "Dormitor · Proiect 01", en: "Bedroom · Project 01" },
    cover: { src: '/images/portfolio/dormitor/dormitor-1/01.jpeg', full: '/images/portfolio/dormitor/dormitor-1/full/01.jpeg', width: 800, height: 600, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom bedroom — Arti Studio Oradea (project 1)" } },
    images: [
      { src: '/images/portfolio/dormitor/dormitor-1/01.jpeg', full: '/images/portfolio/dormitor/dormitor-1/full/01.jpeg', width: 800, height: 600, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom bedroom — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/dormitor/dormitor-1/02.jpeg', full: '/images/portfolio/dormitor/dormitor-1/full/02.jpeg', width: 600, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom bedroom — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/dormitor/dormitor-1/03.jpeg', full: '/images/portfolio/dormitor/dormitor-1/full/03.jpeg', width: 800, height: 600, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom bedroom — Arti Studio Oradea (project 1)" } },
    ],
  },
  {
    id: 'dormitor-dormitor-2',
    category: 'dormitor',
    slug: 'dormitor-2',
    title: { ro: "Dormitor · Proiect 02", en: "Bedroom · Project 02" },
    cover: { src: '/images/portfolio/dormitor/dormitor-2/01.jpeg', full: '/images/portfolio/dormitor/dormitor-2/full/01.jpeg', width: 450, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bedroom — Arti Studio Oradea (project 2)" } },
    images: [
      { src: '/images/portfolio/dormitor/dormitor-2/01.jpeg', full: '/images/portfolio/dormitor/dormitor-2/full/01.jpeg', width: 450, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bedroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dormitor/dormitor-2/02.jpeg', full: '/images/portfolio/dormitor/dormitor-2/full/02.jpeg', width: 600, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bedroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dormitor/dormitor-2/03.jpeg', full: '/images/portfolio/dormitor/dormitor-2/full/03.jpeg', width: 600, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bedroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dormitor/dormitor-2/04.jpeg', full: '/images/portfolio/dormitor/dormitor-2/full/04.jpeg', width: 600, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bedroom — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dormitor/dormitor-2/05.jpeg', full: '/images/portfolio/dormitor/dormitor-2/full/05.jpeg', width: 600, height: 800, alt: { ro: "Dormitor pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom bedroom — Arti Studio Oradea (project 2)" } },
    ],
  },
  {
    id: 'dressing-dresing-1',
    category: 'dressing',
    slug: 'dresing-1',
    title: { ro: "Dressing · Proiect 01", en: "Dressing · Project 01" },
    cover: { src: '/images/portfolio/dressing/dresing-1/01.jpeg', full: '/images/portfolio/dressing/dresing-1/full/01.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom dressing — Arti Studio Oradea (project 1)" } },
    images: [
      { src: '/images/portfolio/dressing/dresing-1/01.jpeg', full: '/images/portfolio/dressing/dresing-1/full/01.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom dressing — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/dressing/dresing-1/02.jpeg', full: '/images/portfolio/dressing/dresing-1/full/02.jpeg', width: 404, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom dressing — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/dressing/dresing-1/03.jpeg', full: '/images/portfolio/dressing/dresing-1/full/03.jpeg', width: 587, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom dressing — Arti Studio Oradea (project 1)" } },
      { src: '/images/portfolio/dressing/dresing-1/04.jpeg', full: '/images/portfolio/dressing/dresing-1/full/04.jpeg', width: 628, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom dressing — Arti Studio Oradea (project 1)" } },
    ],
  },
  {
    id: 'dressing-dresing-2',
    category: 'dressing',
    slug: 'dresing-2',
    title: { ro: "Dressing · Proiect 02", en: "Dressing · Project 02" },
    cover: { src: '/images/portfolio/dressing/dresing-2/01.jpeg', full: '/images/portfolio/dressing/dresing-2/full/01.jpeg', width: 800, height: 600, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom dressing — Arti Studio Oradea (project 2)" } },
    images: [
      { src: '/images/portfolio/dressing/dresing-2/01.jpeg', full: '/images/portfolio/dressing/dresing-2/full/01.jpeg', width: 800, height: 600, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom dressing — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dressing/dresing-2/02.jpeg', full: '/images/portfolio/dressing/dresing-2/full/02.jpeg', width: 800, height: 600, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom dressing — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dressing/dresing-2/03.jpeg', full: '/images/portfolio/dressing/dresing-2/full/03.jpeg', width: 800, height: 600, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom dressing — Arti Studio Oradea (project 2)" } },
      { src: '/images/portfolio/dressing/dresing-2/04.jpeg', full: '/images/portfolio/dressing/dresing-2/full/04.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom dressing — Arti Studio Oradea (project 2)" } },
    ],
  },
  {
    id: 'dressing-dresing-3',
    category: 'dressing',
    slug: 'dresing-3',
    title: { ro: "Dressing · Proiect 03", en: "Dressing · Project 03" },
    cover: { src: '/images/portfolio/dressing/dresing-3/01.jpeg', full: '/images/portfolio/dressing/dresing-3/full/01.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom dressing — Arti Studio Oradea (project 3)" } },
    images: [
      { src: '/images/portfolio/dressing/dresing-3/01.jpeg', full: '/images/portfolio/dressing/dresing-3/full/01.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom dressing — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/dressing/dresing-3/02.jpeg', full: '/images/portfolio/dressing/dresing-3/full/02.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom dressing — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/dressing/dresing-3/03.jpeg', full: '/images/portfolio/dressing/dresing-3/full/03.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom dressing — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/dressing/dresing-3/04.jpeg', full: '/images/portfolio/dressing/dresing-3/full/04.jpeg', width: 600, height: 800, alt: { ro: "Dressing pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom dressing — Arti Studio Oradea (project 3)" } },
    ],
  },
  {
    id: 'living-living-1',
    category: 'living',
    slug: 'living-1',
    title: { ro: "Living · Proiect 01", en: "Living room · Project 01" },
    cover: { src: '/images/portfolio/living/living-1/01.jpeg', full: '/images/portfolio/living/living-1/full/01.jpeg', width: 600, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom living room — Arti Studio Oradea (project 1)" } },
    images: [
      { src: '/images/portfolio/living/living-1/01.jpeg', full: '/images/portfolio/living/living-1/full/01.jpeg', width: 600, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 1)", en: "Custom living room — Arti Studio Oradea (project 1)" } },
    ],
  },
  {
    id: 'living-living-2',
    category: 'living',
    slug: 'living-2',
    title: { ro: "Living · Proiect 02", en: "Living room · Project 02" },
    cover: { src: '/images/portfolio/living/living-2/01.jpeg', full: '/images/portfolio/living/living-2/full/01.jpeg', width: 533, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom living room — Arti Studio Oradea (project 2)" } },
    images: [
      { src: '/images/portfolio/living/living-2/01.jpeg', full: '/images/portfolio/living/living-2/full/01.jpeg', width: 533, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 2)", en: "Custom living room — Arti Studio Oradea (project 2)" } },
    ],
  },
  {
    id: 'living-living-3',
    category: 'living',
    slug: 'living-3',
    title: { ro: "Living · Proiect 03", en: "Living room · Project 03" },
    cover: { src: '/images/portfolio/living/living-3/01.jpeg', full: '/images/portfolio/living/living-3/full/01.jpeg', width: 600, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom living room — Arti Studio Oradea (project 3)" } },
    images: [
      { src: '/images/portfolio/living/living-3/01.jpeg', full: '/images/portfolio/living/living-3/full/01.jpeg', width: 600, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom living room — Arti Studio Oradea (project 3)" } },
      { src: '/images/portfolio/living/living-3/02.jpeg', full: '/images/portfolio/living/living-3/full/02.jpeg', width: 600, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 3)", en: "Custom living room — Arti Studio Oradea (project 3)" } },
    ],
  },
  {
    id: 'living-living-4',
    category: 'living',
    slug: 'living-4',
    title: { ro: "Living · Proiect 04", en: "Living room · Project 04" },
    cover: { src: '/images/portfolio/living/living-4/01.jpeg', full: '/images/portfolio/living/living-4/full/01.jpeg', width: 800, height: 533, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 4)", en: "Custom living room — Arti Studio Oradea (project 4)" } },
    images: [
      { src: '/images/portfolio/living/living-4/01.jpeg', full: '/images/portfolio/living/living-4/full/01.jpeg', width: 800, height: 533, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 4)", en: "Custom living room — Arti Studio Oradea (project 4)" } },
    ],
  },
  {
    id: 'living-living-5',
    category: 'living',
    slug: 'living-5',
    title: { ro: "Living · Proiect 05", en: "Living room · Project 05" },
    cover: { src: '/images/portfolio/living/living-5/01.jpeg', full: '/images/portfolio/living/living-5/full/01.jpeg', width: 800, height: 533, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 5)", en: "Custom living room — Arti Studio Oradea (project 5)" } },
    images: [
      { src: '/images/portfolio/living/living-5/01.jpeg', full: '/images/portfolio/living/living-5/full/01.jpeg', width: 800, height: 533, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 5)", en: "Custom living room — Arti Studio Oradea (project 5)" } },
      { src: '/images/portfolio/living/living-5/02.jpeg', full: '/images/portfolio/living/living-5/full/02.jpeg', width: 602, height: 800, alt: { ro: "Living pe comandă — Arti Studio Oradea (proiect 5)", en: "Custom living room — Arti Studio Oradea (project 5)" } },
    ],
  },
]

export function projectsByCategory(slug: PortfolioCategorySlug): PortfolioProject[] {
  return portfolioProjects.filter((p) => p.category === slug)
}

export function projectBySlug(category: PortfolioCategorySlug, slug: string): PortfolioProject | undefined {
  return portfolioProjects.find((p) => p.category === category && p.slug === slug)
}
