/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleServiciiRouteImport } from './routes/$locale.servicii'
import { Route as LocaleProduseRouteImport } from './routes/$locale.produse'
import { Route as LocalePortofoliuRouteImport } from './routes/$locale.portofoliu'
import { Route as LocaleMaterialeRouteImport } from './routes/$locale.materiale'
import { Route as LocaleGhidRouteImport } from './routes/$locale.ghid'
import { Route as LocaleDespreRouteImport } from './routes/$locale.despre'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleConfidentialitateRouteImport } from './routes/$locale.confidentialitate'
import { Route as LocaleProduseIndexRouteImport } from './routes/$locale.produse.index'
import { Route as LocaleProduseSlugRouteImport } from './routes/$locale.produse.$slug'
import { Route as LocalePortofoliuCategoryRouteImport } from './routes/$locale.portofoliu.$category'
import { Route as LocaleProduseCategorieSlugRouteImport } from './routes/$locale.produse.categorie.$slug'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServiciiRoute = LocaleServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProduseRoute = LocaleProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePortofoliuRoute = LocalePortofoliuRouteImport.update({
  id: '/portofoliu',
  path: '/portofoliu',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMaterialeRoute = LocaleMaterialeRouteImport.update({
  id: '/materiale',
  path: '/materiale',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGhidRoute = LocaleGhidRouteImport.update({
  id: '/ghid',
  path: '/ghid',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDespreRoute = LocaleDespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleConfidentialitateRoute = LocaleConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProduseIndexRoute = LocaleProduseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleProduseRoute,
} as any)
const LocaleProduseSlugRoute = LocaleProduseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleProduseRoute,
} as any)
const LocalePortofoliuCategoryRoute =
  LocalePortofoliuCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => LocalePortofoliuRoute,
  } as any)
const LocaleProduseCategorieSlugRoute =
  LocaleProduseCategorieSlugRouteImport.update({
    id: '/categorie/$slug',
    path: '/categorie/$slug',
    getParentRoute: () => LocaleProduseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/404': typeof R404Route
  '/$locale/confidentialitate': typeof LocaleConfidentialitateRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/despre': typeof LocaleDespreRoute
  '/$locale/ghid': typeof LocaleGhidRoute
  '/$locale/materiale': typeof LocaleMaterialeRoute
  '/$locale/portofoliu': typeof LocalePortofoliuRouteWithChildren
  '/$locale/produse': typeof LocaleProduseRouteWithChildren
  '/$locale/servicii': typeof LocaleServiciiRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/portofoliu/$category': typeof LocalePortofoliuCategoryRoute
  '/$locale/produse/$slug': typeof LocaleProduseSlugRoute
  '/$locale/produse/': typeof LocaleProduseIndexRoute
  '/$locale/produse/categorie/$slug': typeof LocaleProduseCategorieSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/$locale/confidentialitate': typeof LocaleConfidentialitateRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/despre': typeof LocaleDespreRoute
  '/$locale/ghid': typeof LocaleGhidRoute
  '/$locale/materiale': typeof LocaleMaterialeRoute
  '/$locale/portofoliu': typeof LocalePortofoliuRouteWithChildren
  '/$locale/servicii': typeof LocaleServiciiRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/portofoliu/$category': typeof LocalePortofoliuCategoryRoute
  '/$locale/produse/$slug': typeof LocaleProduseSlugRoute
  '/$locale/produse': typeof LocaleProduseIndexRoute
  '/$locale/produse/categorie/$slug': typeof LocaleProduseCategorieSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/404': typeof R404Route
  '/$locale/confidentialitate': typeof LocaleConfidentialitateRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/despre': typeof LocaleDespreRoute
  '/$locale/ghid': typeof LocaleGhidRoute
  '/$locale/materiale': typeof LocaleMaterialeRoute
  '/$locale/portofoliu': typeof LocalePortofoliuRouteWithChildren
  '/$locale/produse': typeof LocaleProduseRouteWithChildren
  '/$locale/servicii': typeof LocaleServiciiRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/portofoliu/$category': typeof LocalePortofoliuCategoryRoute
  '/$locale/produse/$slug': typeof LocaleProduseSlugRoute
  '/$locale/produse/': typeof LocaleProduseIndexRoute
  '/$locale/produse/categorie/$slug': typeof LocaleProduseCategorieSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/404'
    | '/$locale/confidentialitate'
    | '/$locale/contact'
    | '/$locale/despre'
    | '/$locale/ghid'
    | '/$locale/materiale'
    | '/$locale/portofoliu'
    | '/$locale/produse'
    | '/$locale/servicii'
    | '/$locale/'
    | '/$locale/portofoliu/$category'
    | '/$locale/produse/$slug'
    | '/$locale/produse/'
    | '/$locale/produse/categorie/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/$locale/confidentialitate'
    | '/$locale/contact'
    | '/$locale/despre'
    | '/$locale/ghid'
    | '/$locale/materiale'
    | '/$locale/portofoliu'
    | '/$locale/servicii'
    | '/$locale'
    | '/$locale/portofoliu/$category'
    | '/$locale/produse/$slug'
    | '/$locale/produse'
    | '/$locale/produse/categorie/$slug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/404'
    | '/$locale/confidentialitate'
    | '/$locale/contact'
    | '/$locale/despre'
    | '/$locale/ghid'
    | '/$locale/materiale'
    | '/$locale/portofoliu'
    | '/$locale/produse'
    | '/$locale/servicii'
    | '/$locale/'
    | '/$locale/portofoliu/$category'
    | '/$locale/produse/$slug'
    | '/$locale/produse/'
    | '/$locale/produse/categorie/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/servicii': {
      id: '/$locale/servicii'
      path: '/servicii'
      fullPath: '/$locale/servicii'
      preLoaderRoute: typeof LocaleServiciiRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/produse': {
      id: '/$locale/produse'
      path: '/produse'
      fullPath: '/$locale/produse'
      preLoaderRoute: typeof LocaleProduseRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/portofoliu': {
      id: '/$locale/portofoliu'
      path: '/portofoliu'
      fullPath: '/$locale/portofoliu'
      preLoaderRoute: typeof LocalePortofoliuRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/materiale': {
      id: '/$locale/materiale'
      path: '/materiale'
      fullPath: '/$locale/materiale'
      preLoaderRoute: typeof LocaleMaterialeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ghid': {
      id: '/$locale/ghid'
      path: '/ghid'
      fullPath: '/$locale/ghid'
      preLoaderRoute: typeof LocaleGhidRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/despre': {
      id: '/$locale/despre'
      path: '/despre'
      fullPath: '/$locale/despre'
      preLoaderRoute: typeof LocaleDespreRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/confidentialitate': {
      id: '/$locale/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/$locale/confidentialitate'
      preLoaderRoute: typeof LocaleConfidentialitateRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/produse/': {
      id: '/$locale/produse/'
      path: '/'
      fullPath: '/$locale/produse/'
      preLoaderRoute: typeof LocaleProduseIndexRouteImport
      parentRoute: typeof LocaleProduseRoute
    }
    '/$locale/produse/$slug': {
      id: '/$locale/produse/$slug'
      path: '/$slug'
      fullPath: '/$locale/produse/$slug'
      preLoaderRoute: typeof LocaleProduseSlugRouteImport
      parentRoute: typeof LocaleProduseRoute
    }
    '/$locale/portofoliu/$category': {
      id: '/$locale/portofoliu/$category'
      path: '/$category'
      fullPath: '/$locale/portofoliu/$category'
      preLoaderRoute: typeof LocalePortofoliuCategoryRouteImport
      parentRoute: typeof LocalePortofoliuRoute
    }
    '/$locale/produse/categorie/$slug': {
      id: '/$locale/produse/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/$locale/produse/categorie/$slug'
      preLoaderRoute: typeof LocaleProduseCategorieSlugRouteImport
      parentRoute: typeof LocaleProduseRoute
    }
  }
}

interface LocalePortofoliuRouteChildren {
  LocalePortofoliuCategoryRoute: typeof LocalePortofoliuCategoryRoute
}

const LocalePortofoliuRouteChildren: LocalePortofoliuRouteChildren = {
  LocalePortofoliuCategoryRoute: LocalePortofoliuCategoryRoute,
}

const LocalePortofoliuRouteWithChildren =
  LocalePortofoliuRoute._addFileChildren(LocalePortofoliuRouteChildren)

interface LocaleProduseRouteChildren {
  LocaleProduseSlugRoute: typeof LocaleProduseSlugRoute
  LocaleProduseIndexRoute: typeof LocaleProduseIndexRoute
  LocaleProduseCategorieSlugRoute: typeof LocaleProduseCategorieSlugRoute
}

const LocaleProduseRouteChildren: LocaleProduseRouteChildren = {
  LocaleProduseSlugRoute: LocaleProduseSlugRoute,
  LocaleProduseIndexRoute: LocaleProduseIndexRoute,
  LocaleProduseCategorieSlugRoute: LocaleProduseCategorieSlugRoute,
}

const LocaleProduseRouteWithChildren = LocaleProduseRoute._addFileChildren(
  LocaleProduseRouteChildren,
)

interface LocaleRouteChildren {
  LocaleConfidentialitateRoute: typeof LocaleConfidentialitateRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleDespreRoute: typeof LocaleDespreRoute
  LocaleGhidRoute: typeof LocaleGhidRoute
  LocaleMaterialeRoute: typeof LocaleMaterialeRoute
  LocalePortofoliuRoute: typeof LocalePortofoliuRouteWithChildren
  LocaleProduseRoute: typeof LocaleProduseRouteWithChildren
  LocaleServiciiRoute: typeof LocaleServiciiRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleConfidentialitateRoute: LocaleConfidentialitateRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleDespreRoute: LocaleDespreRoute,
  LocaleGhidRoute: LocaleGhidRoute,
  LocaleMaterialeRoute: LocaleMaterialeRoute,
  LocalePortofoliuRoute: LocalePortofoliuRouteWithChildren,
  LocaleProduseRoute: LocaleProduseRouteWithChildren,
  LocaleServiciiRoute: LocaleServiciiRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
